"""Add description field and new tables

Revision ID: a9d172c711e1
Revises: 5c455ad2f222
Create Date: 2025-12-11 14:24:08.540509

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import relationship

# revision identifiers, used by Alembic.
revision: str = "a9d172c711e1"
down_revision: Union[str, Sequence[str], None] = "5c455ad2f222"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
